# Generated by Django 4.1.5 on 2023-04-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('sub_category', models.CharField(default='', max_length=50)),
                ('price', models.ImageField(default=0, upload_to='')),
                ('desc', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='shop/images')),
            ],
        ),
    ]
